### ISSUE TITLE
Update CI/CD

### ISSUE THREAD

**Issue by evanplaice** [vanillawc/vanillawc#26]
Stop tracking `package-lock.json`

## Checklist

- [x] wc-blink
- [x] wc-bullet-chain
- [x] wc-codemirror
- [x] wc-csv-table
- [x] wc-demo
- [x] wc-icon-rule
- [x] wc-include
- [x] wc-markdown
- [x] wc-marquee
- [x] wc-monaco-editor
- [x] wc-resume
- [x] wc-social-link
- [x] wc-sortable-table
- [x] wc-template

## Notes 

*command*
```sh
git rm package-lock.json
```

*latest.yml*
```yaml
name: Latest

on: [push]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install
        run: npm i
      - name: Test
        run: npm run test --if-present
      - name: Lint
        run: npm run lint --if-present
      - name: Types
        run: npm run types --if-present
```

*release.yml*
```yaml
name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Verify
        run: |
          npm i
          npm run preversion
  npm:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Publish
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
        npm publish --access public
  gh:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Publish
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
        ORG="$(echo '${{ github.repository }}' | cut -d'/' -f1)"
        echo "registry=https://npm.pkg.github.com/$ORG" > .npmrc
        npm publish
```
